image: node

before_script:
 # Install ssh-agent if not already installed
 # it is required by Docker
 - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
 
 # Run ssh-agent (inside the build environment)
 - eval $(ssh-agent -s)

 # Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
 # We're using tr to fix line endings which makes ed25519 keys work
 # without extra base64 encoding.
 - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

 # Create the SSH directory and give it the right permissions
 - mkdir -p ~/.ssh
 - chmod 700 ~/.ssh

 # update known hosts
 - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
 - chmod 644 ~/.ssh/known_hosts

deploy_stage:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - yarn install
    - yarn build
    - tar cvf portal.tar build
    - scp ./portal.tar gitlabcli@spotnav.net:/home/portal.tar
    # - ls
    # - scp ./brain gitlabcli@spotnav.net:/home/gitlabcli
    # - ssh gitlabcli@spotnav.net "sudo /bin/systemctl stop brain.service"
    # - ssh gitlabcli@spotnav.net "sudo /bin/mv /home/gitlabcli/brain /home/brain" 
    # - ssh gitlabcli@spotnav.net "sudo /bin/systemctl start brain.service"